// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbKFnmEW_MI6QinzwJ24mt-ssN2Xz4v1I',
    appId: '1:441630274440:web:7d92340bcc713452f3803d',
    messagingSenderId: '441630274440',
    projectId: 'fir-practice-524b5',
    authDomain: 'fir-practice-524b5.firebaseapp.com',
    storageBucket: 'fir-practice-524b5.firebasestorage.app',
    measurementId: 'G-1KC8S7MNRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzf-Pa8ML-PE4RrUYG98mW2WEB4sxwfx0',
    appId: '1:441630274440:android:e5d6dda6ce61b98cf3803d',
    messagingSenderId: '441630274440',
    projectId: 'fir-practice-524b5',
    storageBucket: 'fir-practice-524b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyE58bv9PFtypuSRbP9lrnwSQH8WiQm5I',
    appId: '1:441630274440:ios:bd896f5161dd44bff3803d',
    messagingSenderId: '441630274440',
    projectId: 'fir-practice-524b5',
    storageBucket: 'fir-practice-524b5.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyE58bv9PFtypuSRbP9lrnwSQH8WiQm5I',
    appId: '1:441630274440:ios:bd896f5161dd44bff3803d',
    messagingSenderId: '441630274440',
    projectId: 'fir-practice-524b5',
    storageBucket: 'fir-practice-524b5.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbKFnmEW_MI6QinzwJ24mt-ssN2Xz4v1I',
    appId: '1:441630274440:web:84df8cdf23c83ef5f3803d',
    messagingSenderId: '441630274440',
    projectId: 'fir-practice-524b5',
    authDomain: 'fir-practice-524b5.firebaseapp.com',
    storageBucket: 'fir-practice-524b5.firebasestorage.app',
    measurementId: 'G-4RGS6PRFXH',
  );
}
